spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://db.mobwgwngyzlfassoyiny.supabase.co:5432/postgres
    username: postgres
    password: wXs!4GpBxMb8-gK
  jpa:
    hibernate:
      ddl-auto: none
      open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.security: DEBUG
