spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
    username: ${PGUSER}
    password: ${PGPASSWORD}

  jpa:
    hibernate:
      ddl-auto: update   # ⚠️ use "validate" in production
      open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

  flyway:
    enabled: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info   # ⚠️ safer than "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO


cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

newsapi:
  url: https://newsapi.org/v2
  apiKey: ${NEWS_API_KEY}
  query: (sustainability OR climate OR renewable OR environment OR ESG OR carbon)
  sortBy: publishedAt
  language: en
  pageSize: 50

