spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
    username: ${PGUSER}
    password: ${PGPASSWORD}

  mail:
    from: ${MAIL_FROM}   

  jpa:
    hibernate:
      ddl-auto: none
      open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  server:
    port: ${PORT:5000}

server:
  port: ${PORT}

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

newsapi:
  url: https://newsapi.org/v2
  apiKey: ${NEWS_API_KEY}
  query: (sustainability OR climate OR renewable OR environment OR ESG OR carbon)
  sortBy: publishedAt
  language: en
  pageSize: 50

guardian:
  url: https://content.guardianapis.com
  apiKey: ${GUARDIAN_API_KEY}
  language: en


feed:
  hoursWindow: ${FEED_HOURS_WINDOW}

pagination:
  defaultSize: ${PAGINATION_DEFAULT_SIZE}
  maxSize: ${PAGINATION_MAX_SIZE}

articles:
  latest:
    defaultLimit: ${LATEST_DEFAULT_LIMIT}
    maxLimit: ${LATEST_MAX_LIMIT}

fetching:
  enabled: ${NEWS_FETCHING_ENABLED}
  delay: ${NEWS_FETCHING_DELAY}
  scheduled:
    limit: ${NEWS_FETCHING_SCHEDULED_LIMIT}

synthesis:
  trigger:
    threshold: ${SYNTHESIS_TRIGGER_THRESHOLD}

clustering:
  tfidf:
    threshold: ${CLUSTERING_TFIDF_THRESHOLD}

app:
  frontend-url: ${FRONTEND_URL}
  brand:
    name: ${BRAND_NAME}

google:
  client:
    id=: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  refresh:
    token: ${GOOGLE_REFRESH_TOKEN}
  sender:
    email: ${GOOGLE_SENDER_EMAIL}
  
jwt:
  secret: "${JWT_KEY}"
  expiration-ms: 86400000

security:
  password:
    argon2:
      salt-length: ${SECURITY_PASSWORD_ARGON2_SALT_LENGTH:16}
      hash-length: ${SECURITY_PASSWORD_ARGON2_HASH_LENGTH:32}
      parallelism: ${SECURITY_PASSWORD_ARGON2_PARALLELISM:1}
      memory: ${SECURITY_PASSWORD_ARGON2_MEMORY:8192}
      iterations: ${SECURITY_PASSWORD_ARGON2_ITERATIONS:2}

openai:
  api:
    key: ${OPEN_AI_KEY}

gemini:
  api:
    key: ${GEMINI_API_KEY}
