spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://db.mobwgwngyzlfassoyiny.supabase.co:5432/postgres?sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory

    username: postgres
    password: wXs!4GpBxMb8-gK
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
      open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG
