name: 🚀 Deploy Spring Boot to AWS Elastic Beanstalk

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests

      - name: Prepare deployment bundle
        run: |
          mkdir deploy
          cp target/*.jar deploy/application.jar
          echo "web: java -jar application.jar" > deploy/Procfile
          cd deploy
          zip -r ../deploy.zip .  # ✅ Zip all contents into deploy.zip
          cd ..

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: v-${{ github.run_number }}-${{ github.sha }}
          deployment_package: deploy.zip   # ✅ Use the ZIP file instead of directory
          use_existing_version_if_available: true
